# [build]
#   command = "next build"
#   base = "/client"
#   publish = "/.next"

[build]
  command = "npm run build"
  publish = "out"

# [[redirects]]
#   from = "/*"
#   to = "/:split"
#   status = 200

# [[redirects]]
#     from = "/*"
#     to = "/.netlify/functions/serverless"
#     status = 200
[[plugins]]
  package = "@netlify/plugin-nextjs"