[build]
    command = "next build"
    base = "/client"
    publish = "/.next"

[[redirects]]
  from = "/*"
  to = "https://mollrang.netlify.app/:splat"
  status = 200

[[plugins]]
    package = "@netlify/plugin-nextjs"