[build]
  command = "next build"
  publish = ".next"

# [build]
#   command = "npm run build"
#   base = "client"
#   publish = ".ㅜ"
#
# [[redirects]]
#   from = "/*"
#   to = "/_next/static"
#   status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"