version: '3.8'
services:
  mollrang-dev-server:
    build:
      context: .
      dockerfile: dev-server.dockerfile
    ports:
      - "3030:3000"
    depends_on:
      - mollrang-dev-db
  mollrang-dev-db:
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - "30030:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mollrang
